// Generated by CoffeeScript 1.6.2
(function() {
  define(["ember"], function(Em) {
    var ApplicationView;

    return ApplicationView = Em.View.extend({
      didInsertElement: function() {
        return console.log("application view rendered");
      }
    });
  });

}).call(this);
